routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Models\Document;
use App\Models\Map;
use App\Models\MapEntry;
use App\Models\Place;

use App\Http\Controllers\MapsController;
use App\Http\Controllers\MapLayersController;
use App\Http\Controllers\MapKeysController;
use App\Http\Controllers\MapEntriesController;

use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend/home', [
        'maps_mapping' => Map::where('origin', '=', 'mapping')->orWhere('origin', null)->get(),
        'maps_collection' => Map::where('origin', '=', 'collection')->get(),
    ]);
});

Route::get('/maps/{id}/export', [MapsController::class, 'export'])->name('maps.export');
Route::get('/maps/{id}/images', [MapsController::class, 'images'])->name('maps.images');
Route::post('/maps/{id}/link', [MapsController::class, 'link'])->name('maps.link');
Route::post('/maps/copy', [MapsController::class, 'copy'])->name('maps.copy');
Route::patch('/maps/{id}/imagesUpdate', [MapsController::class, 'imagesUpdate'])->name('maps.imagesUpdate');

/* import */
Route::post('/map-entries/import', [MapEntriesController::class, 'import'])->name('map_entries.import');
Route::post('/map-keys/import', [MapKeysController::class, 'import'])->name('map_keys.import');

/* batch edit */
Route::get('/map-entries/batch/{map_layer_id}', [MapEntriesController::class, 'batch'])->name('map_entries.batch');
Route::post('/map-entries/batch/update', [MapEntriesController::class, 'batchUpdate'])->name('map_entries.batch_update');
Route::get('/map-keys/batch/{map_id}', [MapKeysController::class, 'batch'])->name('map_keys.batch');
Route::post('/map-keys/batch/update', [MapKeysController::class, 'batchUpdate'])->name('map_keys.batch_update');

/* documents */
Route::post('/map-entries/{id}/upload-documents', [MapEntriesController::class, 'uploadDocuments'])->name('map_entries.uploadDocuments');
Route::post('/maps/{id}/upload-documents', [MapsController::class, 'uploadDocuments'])->name('maps.uploadDocuments');

/* resource controllers */
Route::resource('maps', MapsController::Class);
Route::resource('map_layers', MapLayersController::Class);
Route::resource('map_keys', MapKeysController::Class);
Route::resource('map_entries', MapEntriesController::Class);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/import-asv-documents', function () {

    // import/{type}_{question}_{map}_{place}_{notes}.{file_extension}

    $files = Storage::disk('public')->files('import');

    //foreach($files as $key => $item){
    for($i = 0; $i < 200; $i++){

        $item = $files[$i];
        $params = explode('_', $item);

        // get question, map and place from signature
        $question = $params[1];
        $map = $params[2];
        $place = explode('.', $params[3])[0];

        print($item .' '. $question .' '. $map .' '. $place .' '. '<br>');
        
        // move file and create document entry
        $file_name = explode('/', $item)[1];
        $label = implode('.', explode('.', $file_name, -1));

        $document = Document::create([
            'label' => $label,
            'file_name' => $file_name,
            'original_file_name' => $file_name,
            'base_path' => 'documents',
        ]);

        Storage::disk('public')->move($item, 'documents/'.$file_name);

        // get relevant maps with their entries
        $maps = Map::with(['mapEntries']);

        // if question and/or map present, adjust query accordingly
        if($question != '0'){
            $maps->where('label', 'like', '%Frage '.$question.'%');
        } else {
            $maps->where('label', 'like', '%Frage%');
        }
        if($map != '0'){
            $maps->where('label', 'like', '%Karte '.$question.'%');
        } else {
            $maps->where('label', 'like', '%Karte%');
        }

        $maps
            ->whereHas('mapEntries', function($q) use ($place){
                $q->where('map_entries.label', 'like', $place.' %');
            })
            ->get();

        $maps->each(function($el, $i) use ($place, $document){
            print($el->label.'<br>');
            $map_entries = $el->mapEntries()->where('map_entries.label', 'like', $place.' %')->get();

            $map_entries->each(function($el, $i) use ($document){
                print($el->label.'<br>');
                $el->documents()->attach($document);
            });
        });
    }

});


Route::get('/fix-places', function () {
    $map_entries = MapEntry::all();

    $map_entries->each(function($el, $i){
        if($el->place){
            $label = $el->place->label;
            if(Place::where('label', $label)->count() > 1){
                $place = Place::where('label', $label)->orderBy('id', 'asc')->first();
                $el->place_id = $place->id;
                $el->save();
            }
        }
    });
});

Route::get('/remove-leftover-places', function () {
    $map_entries = MapEntry::all();

    $map_entries->each(function($el, $i){
        if($el->place){
            $label = $el->place->label;
            if(Place::where('label', $label)->count() > 1){
                $leftovers = Place::where('label', $label)->doesntHave('mapEntries')->get();
                $leftovers->each(function($leftover, $l){
                    $leftover->delete();
                });
            }
        }
    });
});

Route::get('/fix-place-names', function () {
    $places = Place::all();
    $places->each(function($el, $i){
        $el->label = preg_replace('/([\d]{1,3}a* )/i', '', $el->label);
        $el->save();
    });
});

app/Http/Controllers/MapKeysController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Map;
use App\Models\MapKey;

class MapKeysController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $map = Map::find($request->input('map_id'));
        $key = $map->mapKeys()->create([
            'label' => $request->input('label')
        ]);

        return redirect()->route('map_keys.show', ['map_key' => $key->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('frontend/map-keys/show', [
            'key' => MapKey::find($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $key = MapKey::find($id);

        $key->label = $request->input('label');
        $key->icon = $request->input('icon');

        if($request->file('icon-file')){

            $original_icon_file_name = $request->file('icon-file')->getClientOriginalName();
            $icon_file_name = time().'__'.$original_icon_file_name;

            $key->original_icon_file_name = $original_icon_file_name;
            $key->icon_file_name = $icon_file_name;

            $request->file('icon-file')->storeAs(
                'public/legend-icons', $icon_file_name
            );
        }

        $key->save();

        return redirect()->route('map_keys.show', ['map_key' => $id]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function import(Request $request)
    {
        $rows   = array_map('str_getcsv', $this->remove_utf8_bom(file($request->file('file')->getPathName())));
        $header = array_shift($rows);
        $csv    = array();

        foreach($rows as $row) {
            $csv[] = array_combine($header, $row);
        }

        $map = Map::find($request->input('map_id'));

        foreach($csv as $key => $row) {
            if($row['label'] != '' && !MapKey::where([
                ['label', '=', $row['label']],
                ['map_id', '=', $map->id]
            ])->exists()) {
                $map->mapKeys()->create([
                    'label' => $row['label']
                ]);
            }
        }

        return redirect()->route('maps.show', ['map' => $map->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function batch($id)
    {
        $map = Map::find($id);

        return view('frontend/map-keys/batch', [
            'map' => $map,
            'keys' => $map->mapKeys
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function batchUpdate(Request $request)
    {
        foreach($request->all() as $key => $input) {
            if(strpos($key, 'map-key-id') !== false){
                $key = MapKey::find($input);

                if($request->input('map-key-label-'.$input)){
                    $key->label = $request->input('map-key-label-'.$input);
                }

                if($request->file('icon-file-'.$input)){

                    $key->icon = '';

                    $original_icon_file_name = $request->file('icon-file-'.$input)->getClientOriginalName();
                    $icon_file_name = time().'__'.$original_icon_file_name;

                    $key->original_icon_file_name = $original_icon_file_name;
                    $key->icon_file_name = $icon_file_name;

                    $request->file('icon-file-'.$input)->storeAs(
                        'public/legend-icons', $icon_file_name
                    );
                }

                $key->save();
            }
        }

        return redirect()->route('maps.show', ['map' => $request->input('map_id')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        MapKey::destroy($id);
        return redirect()->route('maps.show', ['map' => $request->input('map_id')]);
    }

    protected function remove_utf8_bom($text)
    {
        $bom = pack('H*','EFBBBF');
        $text = preg_replace("/^$bom/", '', $text);
        return $text;
    }
}

resources/views/frontend/map-keys/batch.blade.php
@extends('frontend/base')

@section('content')

<x-header>
    <div class="flex flex-1 justify-end">
        <a href="{{ route('maps.show', ['map' => $map->id]) }}" class="ml-2 hover:underline">Map</a>
    </div>
</x-header>

<div class="flex min-h-screen">
    <aside class="w-1/3 shadow-2xl z-40" style="padding-top: 45px;">
        <div>
            <form id="map_keys_form" enctype="multipart/form-data" method="POST" action="{{ route('map_keys.batch_update') }}">
                @csrf

                <input type="hidden" name="map_id" value="{{ $map->id }}">

                @foreach ($keys as $key)
                    <div class="py-2 px-4 border-b">
                        <input type="hidden" name="map-key-id-{{ $key->id }}" value="{{ $key->id }}">
                        <input type="text" class="block w-full" name="map-key-label-{{ $key->id }}" value="{{ $key->label }}">
                        @if($key->icon_file_name)<img src="/storage/legend-icons/{{ $key->icon_file_name }}" class="inline-block" style="width: 14px; position: relative; top: -3px;">@else &mdash; @endif
                        <input class="text-xs" type="file" name="icon-file-{{ $key->id }}" accept="image/*">
                    </div>
                @endforeach
                
                <div class="text-right mt-4 px-4 flex justify-between">
                    <a href="{{ route('maps.show', ['map' => $map->id]) }}" class="hover:underline">Back</a>
                    <x-fe-button>Save</x-fe-button>
                </div>
            </form>
        </div>
    </aside>

    <div class="flex-1 h-full w-2/3 fixed right-0" style="padding-top: 45px;">
        @include('frontend/maps/render', [
            'map' => $map,
            'layers' => $map->mapLayers
        ])
    </div>
</div>
@endsection

resources/views/frontend/map-keys/show.blade.php
@extends('frontend/base')

@section('content')

<x-header>
    <div class="flex flex-1 justify-end">
        <a href="{{ route('maps.show', ['map' => $key->map->id]) }}" class="ml-2 hover:underline">Map</a>
    </div>
</x-header>

<div class="flex min-h-screen">
    <aside class="w-1/3 shadow-2xl z-40" style="padding-top: 45px;">
        <div>
            <form method="POST" enctype="multipart/form-data" action="{{ route('map_keys.update', ['map_key' => $key->id]) }}">
                @csrf
                @method('patch')

                <input class="py-2 px-4 text-xl border-b border-black bg-gray-100 flex justify-between font-bold w-full" type="text" name="label" placeholder="Label" value="{{ $key->label }}" required>

                <div x-data="{show_picker: false, emoji: ''}" class="py-2 px-4 relative w-full justify-between border-b border-gray-400">
                    <emoji-picker class="absolute top-0 right-0" x-show="show_picker" @emoji-click="() => {
                        show_picker = false;
                        $refs.emojiicon.value = event.detail.unicode;    
                    }"></emoji-picker>
                    <input x-ref="emojiicon" class="w-full mb-2" type="text" name="icon" placeholder="Icon" value="{{ $key->icon }}">
                    <x-fe-button type="button" @click="show_picker = ! show_picker; console.log(show_picker)">Emoji</x-fe-button>
                </div>

                <div x-data class="py-2 px-4 w-full justify-between border-b border-gray-400">
                    <span class="file-name {{ $key->original_icon_file_name == '' ? 'is-hidden' : '' }} pia-icon_file-label mb-2 w-full inline-block">
                        {{$key->original_icon_file_name}}
                    </span>
                    <x-fe-button type="button" @click="$refs.file.click()">Choose image file</x-fe-button>
                    <input x-ref="file" class="file-input pia-icon_file-input hidden" type="file" name="icon-file" accept="image/*">
                </div>


                <div class="text-right mt-4 px-4 flex justify-between">
                    <a href="{{ route('maps.show', ['map' => $key->map->id]) }}" class="hover:underline">Back</a>
                    <x-fe-button>Save</x-fe-button>
                </div>
            </form>
        </div>
        <form method="POST" action="{{ route('map_keys.destroy', ['map_key' => $key->id]) }}" onsubmit="return confirm('Do you really want to delete this map key?');">
            @csrf
            @method('delete')
            <input type="hidden" name="map_id" value="{{ $key->map->id }}">
            <button class="absolute bottom-4 border border-red-500 bg-red-500 text-white hover:bg-white hover:text-red-500 p-1 px-6 transition uppercase text-xs ml-4" type="submit">Delete Map Key</button>
        </form>
    </aside>

    <div class="w-2/3 h-screen bg-gray-200"></div>
</div>
@endsection

@section('scripts')
<script type="module" src="https://cdn.jsdelivr.net/npm/emoji-picker-element@^1/index.js"></script>
<script>

    let icon_file_input = document.querySelector('.pia-icon_file-input'),
        icon_file_label = document.querySelector('.pia-icon_file-label');

    icon_file_input.addEventListener('change', e => {
        icon_file_label.classList.remove('is-hidden');
        icon_file_label.innerHTML = icon_file_input.files[0].name;
    });

</script>
@endsection