routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Models\Document;
use App\Models\Map;
use App\Models\MapEntry;
use App\Models\Place;

use App\Http\Controllers\MapsController;
use App\Http\Controllers\MapLayersController;
use App\Http\Controllers\MapKeysController;
use App\Http\Controllers\MapEntriesController;

use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend/home', [
        'maps_mapping' => Map::where('origin', '=', 'mapping')->orWhere('origin', null)->get(),
        'maps_collection' => Map::where('origin', '=', 'collection')->get(),
    ]);
});

Route::get('/maps/{id}/export', [MapsController::class, 'export'])->name('maps.export');
Route::get('/maps/{id}/images', [MapsController::class, 'images'])->name('maps.images');
Route::post('/maps/{id}/link', [MapsController::class, 'link'])->name('maps.link');
Route::post('/maps/copy', [MapsController::class, 'copy'])->name('maps.copy');
Route::patch('/maps/{id}/imagesUpdate', [MapsController::class, 'imagesUpdate'])->name('maps.imagesUpdate');

/* import */
Route::post('/map-entries/import', [MapEntriesController::class, 'import'])->name('map_entries.import');
Route::post('/map-keys/import', [MapKeysController::class, 'import'])->name('map_keys.import');

/* batch edit */
Route::get('/map-entries/batch/{map_layer_id}', [MapEntriesController::class, 'batch'])->name('map_entries.batch');
Route::post('/map-entries/batch/update', [MapEntriesController::class, 'batchUpdate'])->name('map_entries.batch_update');
Route::get('/map-keys/batch/{map_id}', [MapKeysController::class, 'batch'])->name('map_keys.batch');
Route::post('/map-keys/batch/update', [MapKeysController::class, 'batchUpdate'])->name('map_keys.batch_update');

/* documents */
Route::post('/map-entries/{id}/upload-documents', [MapEntriesController::class, 'uploadDocuments'])->name('map_entries.uploadDocuments');
Route::post('/maps/{id}/upload-documents', [MapsController::class, 'uploadDocuments'])->name('maps.uploadDocuments');

/* resource controllers */
Route::resource('maps', MapsController::Class);
Route::resource('map_layers', MapLayersController::Class);
Route::resource('map_keys', MapKeysController::Class);
Route::resource('map_entries', MapEntriesController::Class);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/import-asv-documents', function () {

    // import/{type}_{question}_{map}_{place}_{notes}.{file_extension}

    $files = Storage::disk('public')->files('import');

    //foreach($files as $key => $item){
    for($i = 0; $i < 200; $i++){

        $item = $files[$i];
        $params = explode('_', $item);

        // get question, map and place from signature
        $question = $params[1];
        $map = $params[2];
        $place = explode('.', $params[3])[0];

        print($item .' '. $question .' '. $map .' '. $place .' '. '<br>');
        
        // move file and create document entry
        $file_name = explode('/', $item)[1];
        $label = implode('.', explode('.', $file_name, -1));

        $document = Document::create([
            'label' => $label,
            'file_name' => $file_name,
            'original_file_name' => $file_name,
            'base_path' => 'documents',
        ]);

        Storage::disk('public')->move($item, 'documents/'.$file_name);

        // get relevant maps with their entries
        $maps = Map::with(['mapEntries']);

        // if question and/or map present, adjust query accordingly
        if($question != '0'){
            $maps->where('label', 'like', '%Frage '.$question.'%');
        } else {
            $maps->where('label', 'like', '%Frage%');
        }
        if($map != '0'){
            $maps->where('label', 'like', '%Karte '.$question.'%');
        } else {
            $maps->where('label', 'like', '%Karte%');
        }

        $maps
            ->whereHas('mapEntries', function($q) use ($place){
                $q->where('map_entries.label', 'like', $place.' %');
            })
            ->get();

        $maps->each(function($el, $i) use ($place, $document){
            print($el->label.'<br>');
            $map_entries = $el->mapEntries()->where('map_entries.label', 'like', $place.' %')->get();

            $map_entries->each(function($el, $i) use ($document){
                print($el->label.'<br>');
                $el->documents()->attach($document);
            });
        });
    }

});


Route::get('/fix-places', function () {
    $map_entries = MapEntry::all();

    $map_entries->each(function($el, $i){
        if($el->place){
            $label = $el->place->label;
            if(Place::where('label', $label)->count() > 1){
                $place = Place::where('label', $label)->orderBy('id', 'asc')->first();
                $el->place_id = $place->id;
                $el->save();
            }
        }
    });
});

Route::get('/remove-leftover-places', function () {
    $map_entries = MapEntry::all();

    $map_entries->each(function($el, $i){
        if($el->place){
            $label = $el->place->label;
            if(Place::where('label', $label)->count() > 1){
                $leftovers = Place::where('label', $label)->doesntHave('mapEntries')->get();
                $leftovers->each(function($leftover, $l){
                    $leftover->delete();
                });
            }
        }
    });
});

Route::get('/fix-place-names', function () {
    $places = Place::all();
    $places->each(function($el, $i){
        $el->label = preg_replace('/([\d]{1,3}a* )/i', '', $el->label);
        $el->save();
    });
});

app/Http/Controllers/MapEntriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Map;
use App\Models\MapLayer;
use App\Models\MapEntry;
use App\Models\MapKey;
use App\Models\Place;
use App\Models\Image;

class MapEntriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $layer = MapLayer::find($request->input('layer_id'));
        $entry = $layer->mapEntries()->create([
            'label' => $request->input('label'),
            'type' => $request->input('type')
        ]);
        
        /*if($entry->type == 1) {
            $place = Place::create([
                'label' => $entry->label,
                'origin' => 'mapping'
            ]);

            $entry->place_id = $place->id;
            $entry->save();
        }*/
        if($entry->type == 3) {
            $image = Image::create([
                'title' => $entry->label,
                'base_path' => 'upload'
            ]);

            $entry->image_id = $image->id;
            $entry->save();
        }
        if($entry->type == 4) {
            $image = Image::create([
                'title' => $entry->label,
                'base_path' => 'upload'
            ]);
            $place = Place::create([
                'label' => $entry->label,
                'origin' => 'mapping'
            ]);

            $entry->place_id = $place->id;
            $entry->image_id = $image->id;
            $entry->save();
        }

        return redirect()->route('map_entries.show', ['map_entry' => $entry->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $entry = MapEntry::find($id);

        return view('frontend/map-entries/show', [
            'editable_entry' => $entry,
            'keys' => $entry->mapLayer->map->mapKeys,
            'places' => Place::all()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $entry = MapEntry::find($id);

        $entry->label = $request->input('label');
        $entry->description = $request->input('description');
        $entry->map_layer_id = $request->input('layer_id');

        $entry->mapKeys()->sync($request->input('keys'));
        
        if($entry->type == 1) {

            if($entry->place_id == $request->place_id && $request->place_id != ''){
                $entry->place->latitude = $request->input('latitude');
                $entry->place->longitude = $request->input('longitude');
            } else {
                $entry->place_id = $request->place_id;
            }

            $entry->push();

            if(!$entry->place) {
                if($request->latitude != '' && $request->longitude != '' && $request->place_id == ''){
                    $place = Place::create([
                        'label' => $entry->label,
                        'origin' => 'mapping',
                        'latitude' => $request->latitude,
                        'longitude' => $request->longitude
                    ]);
                    $entry->place_id = $place->id;
                    $entry->save();
                }
            }
        }

        if(in_array($entry->type, [3, 4])) {
            $image = Image::find($entry->image_id);
            $image->title = $entry->label;

            if($request->file('image')){
                // $curl = curl_init();

                // curl_setopt_array($curl, array(
                // CURLOPT_URL => 'https://sipi.participatory-archives.ch/server/upload-pia.elua',
                // CURLOPT_RETURNTRANSFER => true,
                // CURLOPT_ENCODING => '',
                // CURLOPT_MAXREDIRS => 10,
                // CURLOPT_TIMEOUT => 0,
                // CURLOPT_FOLLOWLOCATION => true,
                // CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                // CURLOPT_CUSTOMREQUEST => 'POST',
                // // @TODO: fix those damn ssl problems
                // CURLOPT_SSL_VERIFYHOST => false,
                // CURLOPT_SSL_VERIFYPEER => false,
                // CURLOPT_POSTFIELDS => array(
                //         'Datei'=> new \CURLFile(
                //             $request->file('image')->getPathName()
                //         ),
                //         'Cuse_sop' => 'yes'
                //     ),
                // ));

                // $response = curl_exec($curl);

                // $data = json_decode($response);

                // $image->signature = $data->signature;

                $original_file_name = $request->file('image')->getClientOriginalName();
                $file_name = time().'__'.$original_file_name;

                $image->original_file_name = $original_file_name;
                $image->file_name = $file_name;

                $request->file('image')->storeAs(
                    'public/uploads', $file_name
                );
            }

            $image->save();
        }

        if(in_array($entry->type, [2, 3])) {
            $entry->complex_data = $request->input('complex_data');
        }

        if($entry->type == 4) {
            $entry->place->label = $entry->label;
            $entry->place->latitude = $request->input('latitude');
            $entry->place->longitude = $request->input('longitude');
        }

        $entry->push();

        return redirect()->route('map_entries.show', ['map_entry' => $entry->id]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function import(Request $request)
    {
        $rows   = array_map('str_getcsv', $this->remove_utf8_bom(file($request->file('file')->getPathName())));
        $header = array_shift($rows);
        $csv    = array();

        foreach($rows as $row) {
            $csv[] = array_combine($header, $row);
        }

        $map = Map::find($request->input('map_id'));
        $layer = $map->mapLayers()->create([
            'label' => $request->file('file')->getClientOriginalName()
        ]);

        foreach($csv as $key => $row) {

            $type = 1;
            if(isset($row['type'])){
                $type = $row['type'];
            }
    
            $label = '';
            if(isset($row['label'])){
                $label = $row['label'];
            }
    
            $description = '';
            if(isset($row['description'])){
                $description = $row['description'];
            }

            $entry = $layer->mapEntries()->create([
                'label' => $label,
                'description' => $description,
                'type' => $type
            ]);
            
            if($type == 1) {
                $place = Place::create([
                    'label' => $label,
                    'latitude' => $row['latitude'],
                    'longitude' => $row['longitude'],
                    'origin' => 'mapping'
                ]);

                $entry->place_id = $place->id;
                $entry->save();
            }
            
            if($type == 2) {
                $entry->complex_data = $row['geojson'];
                $entry->save();
            }

            $keys = [];

            foreach(explode(',', $row['keys']) as $key => $label) {
                $label = trim($label);
                if(!MapKey::where('label', $label)
                    ->where('map_id', $map->id)->exists()) {
                    $keys[] = $map->mapKeys()->create([
                        'label' => $label
                    ])->id;
                } else {
                    $keys[] = MapKey::where('label', $label)
                            ->where('map_id', $map->id)->first()->id;
                }
            }

            $entry->mapKeys()->sync($keys);
        }

        return redirect()->route('maps.show', ['map' => $map->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function batch($id)
    {
        $layer = MapLayer::find($id);

        return view('frontend/map-entries/batch', [
            'layer' => $layer,
            'entries' => $layer->mapEntries,
            'keys' => $layer->map->mapKeys
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function batchUpdate(Request $request)
    {
        foreach($request->all() as $key => $input) {
            if(strpos($key, 'map-entry') !== false){
                $entry = MapEntry::find($input);
                $entry->label = $request->input('label-'.$input);
                $entry->mapKeys()->sync($request->input('keys-'.$input));

                $entry->save();
            }
        }
        return redirect()->route('map_entries.batch', ['map_layer_id' => $request->input('map_layer_id')]);
    }

    
    /**
     * Update the specified resource in storage.
     *

resources/views/frontend/map-entries/batch.blade.php
@extends('frontend/base')

@section('content')

<x-header>
    <div class="flex flex-1 justify-end">
        <a href="{{ route('maps.show', ['map' => $layer->map->id]) }}" class="ml-2 hover:underline">Map</a>
    </div>
</x-header>

<div class="flex min-h-screen">
    <aside class="w-1/3 shadow-2xl z-40" style="padding-top: 45px;">
        <div>
            <form id="map_entry_form" method="POST" action="{{ route('map_entries.batch_update') }}">
                @csrf

                <input type="hidden" name="map_layer_id" value="{{ $layer->id }}">

                @foreach ($entries->sortBy('label', SORT_NATURAL , false) as $entry)
                    <div class="py-2 px-4">
                        <input type="hidden" name="map-entry-{{ $entry->id }}" value="{{ $entry->id }}">
                        <input type="text" name="label-{{ $entry->id }}" value="{{ $entry->label }}" class="w-full"/>
                        <select id="map-keys-{{ $entry->id }}" class="text-sm inline-block w-full mt-1" name="keys-{{ $entry->id }}[]" multiple size="10">
                            
                        </select>
                    </div>
                @endforeach
                
                <div class="text-right mt-4 px-4 flex justify-between">
                    <a href="{{ route('maps.show', ['map' => $layer->map->id]) }}" class="hover:underline">Back</a>
                    <x-fe-button>Save</x-fe-button>
                </div>
            </form>
        </div>
    </aside>

    <div class="flex-1 h-full w-2/3 fixed right-0" style="padding-top: 45px;">
        @include('frontend/maps/render', [
            'map' => $layer->map,
            'layers' => $layer->map->mapLayers
        ])
    </div>
</div>
@endsection

@section('scripts')
<script>

    document.addEventListener('DOMContentLoaded', () => {
        @foreach ($entries as $entry)
            new SlimSelect({
                select: '#map-keys-{{ $entry->id }}',
                placeholder: 'Select Legend Keys',
                data: [
                    @foreach($keys as $key)
                        {
                            innerHTML: '@if($key->icon_file_name)<img src="/storage/legend-icons/{{ $key->icon_file_name }}" class="inline-block" style="height: 18px; position: relative; top: -2px;">@endif {{ $key->icon }} {{ $key->label }}',
                            text: '{{ $key->label }}',
                            value: '{{ $key->id }}',
                            selected: {{ $entry->mapKeys->contains($key) ? 'true' : 'false' }}
                        },
                    @endforeach
                ]
            });
        @endforeach
    });
    
</script>
@endsection

resources/views/frontend/map-entries/show.blade.php
@extends('frontend/base')

@section('content')

<x-header>
    <div class="flex flex-1 justify-end">
        <a href="{{ route('maps.show', ['map' => $editable_entry->mapLayer->map->id]) }}" class="ml-2 hover:underline">Map</a>
    </div>
</x-header>

<div class="flex min-h-screen">
    <aside class="w-1/3 shadow-2xl z-40" style="padding-top: 45px;">
        <div>
            <form id="map_entry_form" method="POST" enctype="multipart/form-data" action="{{ route('map_entries.update', ['map_entry' => $editable_entry->id]) }}">
                @csrf
                @method('patch')
                <input type="hidden" name="map_id" value="{{ $editable_entry->mapLayer->map->id }}">
                <input type="hidden" name="layer_id" value="{{ $editable_entry->mapLayer->id }}">
                
                @if (in_array($editable_entry->type, [2,3]))
                <input type="hidden" name="complex_data" value="{{ $editable_entry->complex_data }}">
                @endif

                <input class="py-2 px-4 text-xl border-b border-black bg-gray-100 flex justify-between font-bold w-full" type="text" name="label" placeholder="Label" value="{{ $editable_entry->label }}" required>
                <!--<textarea class="textarea" name="description" placeholder="Beschreibung">{{ $editable_entry->description }}</textarea>-->

                @if (in_array($editable_entry->type, [1, 4]))
                <div class="flex">
                    <input type="text" class="py-2 px-4 focus:outline-none w-1/2 text-xs border-b border-black bg-gray" name="latitude" value="{{ $editable_entry->place->latitude ?? '' }}" placeholder="Latitude">
                    <input type="text" class="py-2 px-4 focus:outline-none w-1/2 text-xs border-b border-black bg-gray" name="longitude" value="{{ $editable_entry->place->longitude ?? '' }}" placeholder="Longitude">
                </div>
                @endif

                @if (in_array($editable_entry->type, [3, 4]))
                    <div x-data class="py-2 px-4 w-full justify-between border-b border-gray-400">
                        <span class="file-name {{ $editable_entry->image->original_file_name == '' ? 'is-hidden' : '' }} pia-image-label mb-2 w-full inline-block">
                            {{$editable_entry->image->original_file_name}}
                        </span>
                        <x-fe-button type="button" @click="$refs.file.click()">Choose image file</x-fe-button>
                        <input x-ref="file" class="file-input pia-image-input hidden" type="file" name="image" accept="image/*">
                    </div>
                @endif

                <h2 class="py-2 px-4 text-md">Choose/Change existing place</h2>
                <select id="places" class="text-sm inline-block w-full py-2 px-4" name="place_id">
                    <option value="">&mdash;</option>
                    @foreach($places as $place)
                        <option value="{{ $place->id }}" {{ ($editable_entry->place->id ?? -1) == $place->id ? 'selected="selected"' : '' }}>{{ $place->label }}</option>
                    @endforeach
                </select>
                @if($editable_entry->place)
                <p class="px-4 text-right"><a class="text-xs underline" href="https://pia.dhlab.unibas.ch/places/{{ $editable_entry->place->id }}">View/Edit place details</a></p>
                @endif

                @if (count($keys))
                <h2 class="py-2 px-4 text-lg">
                    Legend Keys
                </h2>
                <select id="map-keys" class="text-sm inline-block w-full py-2 px-4 " name="keys[]" multiple size="10">
                </select>
                @endif

                <div class="text-right mt-4 px-4 flex justify-between">
                    <a href="{{ route('maps.show', ['map' => $editable_entry->mapLayer->map->id]) }}" class="hover:underline">Back</a>
                    <x-fe-button>Save</x-fe-button>
                </div>

            </form>
        </div>

        <div class="p-4">
            <h2 class="text-lg">
                Documents
            </h2>
            @if(count($editable_entry->documents))
            <ul class="py-2">
                @foreach ($editable_entry->documents as $document)
                <li class="mb-2">
                    &mdash; <a class="underline text-sm" href="/{{ 'storage/' . $document->base_path . '/' . $document->file_name }}">{{ $document->label }}</a>
                </li>
                @endforeach
            </ul>
            @endif
            <form class="flex justify-between inline-block" method="POST" enctype="multipart/form-data"
                action="{{ route('map_entries.uploadDocuments', [$editable_entry]) }}">
                @csrf
                <input type="file" name="documents[]" required multiple>
                <x-fe-button>Upload</x-fe-button>
            </form>
        </div>

        <form method="POST" action="{{ route('map_entries.destroy', ['map_entry' => $editable_entry->id]) }}" onsubmit="return confirm('Do you really want to delete this entry?');">
            @csrf
            @method('delete')
            <input type="hidden" name="map_id" value="{{ $editable_entry->mapLayer->map->id }}">
            <button class="absolute bottom-4 border border-red-500 bg-red-500 text-white hover:bg-white hover:text-red-500 p-1 px-6 transition uppercase text-xs ml-4" type="submit">Delete Entry</button>
        </form>
    </aside>

    <div class="flex-1 h-full w-2/3 fixed right-0" style="padding-top: 45px;">
        @include('frontend/maps/render', [
            'map' => $editable_entry->mapLayer->map,
            'layers' => $editable_entry->mapLayer->map->mapLayers
        ])
    </div>
</div>
@endsection

@section('scripts')
<script>

    document.addEventListener('DOMContentLoaded', () => {
        @if (count($keys))
        new SlimSelect({
            select: '#map-keys',
            placeholder: 'Select Legend Keys',
            data: [
                @foreach($keys as $key)
                    {
                        innerHTML: '@if($key->icon_file_name)<img src="/storage/legend-icons/{{ $key->icon_file_name }}" class="inline-block" style="height: 18px; position: relative; top: -2px;">@endif {{ $key->icon }} {{ $key->label }}',
                        text: '{{ $key->label }}',
                        value: '{{ $key->id }}',
                        selected: {{ $editable_entry->mapKeys->contains($key) ? 'true' : 'false' }}
                    },
                @endforeach
            ]
        });
        @endif

        new SlimSelect({
            select: '#places',
        });
    });
    
</script>
@endsection