routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Models\Document;
use App\Models\Map;
use App\Models\MapEntry;
use App\Models\Place;

use App\Http\Controllers\MapsController;
use App\Http\Controllers\MapLayersController;
use App\Http\Controllers\MapKeysController;
use App\Http\Controllers\MapEntriesController;

use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend/home', [
        'maps_mapping' => Map::where('origin', '=', 'mapping')->orWhere('origin', null)->get(),
        'maps_collection' => Map::where('origin', '=', 'collection')->get(),
    ]);
});

Route::get('/maps/{id}/export', [MapsController::class, 'export'])->name('maps.export');
Route::get('/maps/{id}/images', [MapsController::class, 'images'])->name('maps.images');
Route::post('/maps/{id}/link', [MapsController::class, 'link'])->name('maps.link');
Route::post('/maps/copy', [MapsController::class, 'copy'])->name('maps.copy');
Route::patch('/maps/{id}/imagesUpdate', [MapsController::class, 'imagesUpdate'])->name('maps.imagesUpdate');

/* import */
Route::post('/map-entries/import', [MapEntriesController::class, 'import'])->name('map_entries.import');
Route::post('/map-keys/import', [MapKeysController::class, 'import'])->name('map_keys.import');

/* batch edit */
Route::get('/map-entries/batch/{map_layer_id}', [MapEntriesController::class, 'batch'])->name('map_entries.batch');
Route::post('/map-entries/batch/update', [MapEntriesController::class, 'batchUpdate'])->name('map_entries.batch_update');
Route::get('/map-keys/batch/{map_id}', [MapKeysController::class, 'batch'])->name('map_keys.batch');
Route::post('/map-keys/batch/update', [MapKeysController::class, 'batchUpdate'])->name('map_keys.batch_update');

/* documents */
Route::post('/map-entries/{id}/upload-documents', [MapEntriesController::class, 'uploadDocuments'])->name('map_entries.uploadDocuments');
Route::post('/maps/{id}/upload-documents', [MapsController::class, 'uploadDocuments'])->name('maps.uploadDocuments');

/* resource controllers */
Route::resource('maps', MapsController::Class);
Route::resource('map_layers', MapLayersController::Class);
Route::resource('map_keys', MapKeysController::Class);
Route::resource('map_entries', MapEntriesController::Class);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/import-asv-documents', function () {

    // import/{type}_{question}_{map}_{place}_{notes}.{file_extension}

    $files = Storage::disk('public')->files('import');

    //foreach($files as $key => $item){
    for($i = 0; $i < 200; $i++){

        $item = $files[$i];
        $params = explode('_', $item);

        // get question, map and place from signature
        $question = $params[1];
        $map = $params[2];
        $place = explode('.', $params[3])[0];

        print($item .' '. $question .' '. $map .' '. $place .' '. '<br>');
        
        // move file and create document entry
        $file_name = explode('/', $item)[1];
        $label = implode('.', explode('.', $file_name, -1));

        $document = Document::create([
            'label' => $label,
            'file_name' => $file_name,
            'original_file_name' => $file_name,
            'base_path' => 'documents',
        ]);

        Storage::disk('public')->move($item, 'documents/'.$file_name);

        // get relevant maps with their entries
        $maps = Map::with(['mapEntries']);

        // if question and/or map present, adjust query accordingly
        if($question != '0'){
            $maps->where('label', 'like', '%Frage '.$question.'%');
        } else {
            $maps->where('label', 'like', '%Frage%');
        }
        if($map != '0'){
            $maps->where('label', 'like', '%Karte '.$question.'%');
        } else {
            $maps->where('label', 'like', '%Karte%');
        }

        $maps
            ->whereHas('mapEntries', function($q) use ($place){
                $q->where('map_entries.label', 'like', $place.' %');
            })
            ->get();

        $maps->each(function($el, $i) use ($place, $document){
            print($el->label.'<br>');
            $map_entries = $el->mapEntries()->where('map_entries.label', 'like', $place.' %')->get();

            $map_entries->each(function($el, $i) use ($document){
                print($el->label.'<br>');
                $el->documents()->attach($document);
            });
        });
    }

});


Route::get('/fix-places', function () {
    $map_entries = MapEntry::all();

    $map_entries->each(function($el, $i){
        if($el->place){
            $label = $el->place->label;
            if(Place::where('label', $label)->count() > 1){
                $place = Place::where('label', $label)->orderBy('id', 'asc')->first();
                $el->place_id = $place->id;
                $el->save();
            }
        }
    });
});

Route::get('/remove-leftover-places', function () {
    $map_entries = MapEntry::all();

    $map_entries->each(function($el, $i){
        if($el->place){
            $label = $el->place->label;
            if(Place::where('label', $label)->count() > 1){
                $leftovers = Place::where('label', $label)->doesntHave('mapEntries')->get();
                $leftovers->each(function($leftover, $l){
                    $leftover->delete();
                });
            }
        }
    });
});

Route::get('/fix-place-names', function () {
    $places = Place::all();
    $places->each(function($el, $i){
        $el->label = preg_replace('/([\d]{1,3}a* )/i', '', $el->label);
        $el->save();
    });
});

app/Http/Controllers/MapLayersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\MapLayer;

class MapLayersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $map_layer = MapLayer::create([
            'label' => $request->label,
            'map_id' => $request->map_id,
            'zoom_min' => $request->zoom_min,
            'zoom_max' => $request->zoom_max
        ]);

        return redirect()->route('map_layers.show', ['map_layer' => $map_layer->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('frontend/map-layers/show', [
            'map_layer' => MapLayer::find($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $map_layer = MapLayer::find($id);

        $map_layer->label = $request->label;
        $map_layer->zoom_min = $request->zoom_min;
        $map_layer->zoom_max = $request->zoom_max;

        $map_layer->save();

        return redirect()->route('map_layers.show', ['map_layer' => $map_layer->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        MapLayer::destroy($id);
        return redirect()->route('maps.show', ['map' => $request->input('map_id')]);
    }
}

resources/views/frontend/map-layers/show.blade.php
@extends('frontend/base')

@section('content')

<x-header>
    <div class="flex flex-1 justify-end">
        <a href="{{ route('maps.show', ['map' => $map_layer->map->id]) }}" class="ml-2 hover:underline">Map</a>
    </div>
</x-header>

<div class="flex min-h-screen">
    <aside class="w-1/3 shadow-2xl z-40" style="padding-top: 45px;">
        <div>
            <form method="POST" action="{{ route('map_layers.update', ['map_layer' => $map_layer->id]) }}">
                @csrf
                @method('patch')

                <input class="py-2 px-4 text-xl border-b border-black bg-gray-100 flex justify-between font-bold w-full" type="text" name="label" placeholder="Label" value="{{ $map_layer->label }}" required>

                <div class="p-4">
                    <span class="mb-4 inline-block">Show layer <em>from/to</em> zoom level.</span>
                    <div class="flex">
                        <div class="w-1/2 pr-2">
                            <label for="zoom_min" class="text-xs block">From</label>
                            <select name="zoom_min" id="zoom_min" class="w-full">
                                @for ($i = 0; $i <= 18; $i++)
                                    <option value="{{ $i }}" {{ $map_layer->zoom_min == $i ? 'selected' : '' }}>
                                        {{ $i }}
                                        {{ $i == 0 ? ' - Globe' : '' }}
                                        {{ $i == 8 ? ' - Country' : '' }}
                                        {{ $i == 11 ? ' - State' : '' }}
                                        {{ $i == 14 ? ' - City' : '' }}
                                        {{ $i == 18 ? ' - Closest' : '' }}
                                    </option>
                                @endfor
                            </select>
                        </div>
                        <div class="w-1/2">
                            <label for="zoom_max" class="text-xs block">To</label>
                            <select name="zoom_max" id="zoom_max" class="w-full">
                                @for ($i = 0; $i <= 18; $i++)
                                    <option value="{{ $i }}" {{ ($map_layer->zoom_max ?? 18) == $i ? 'selected' : '' }}>
                                        {{ $i }}
                                        {{ $i == 0 ? ' - Globe' : '' }}
                                        {{ $i == 8 ? ' - Country' : '' }}
                                        {{ $i == 11 ? ' - State' : '' }}
                                        {{ $i == 14 ? ' - City' : '' }}
                                        {{ $i == 18 ? ' - Closest' : '' }}
                                    </option>
                                @endfor
                            </select>
                        </div>
                    </div>
                </div>

                <div class="text-right mt-4 px-4 flex justify-between">
                    <a href="{{ route('maps.show', ['map' => $map_layer->map->id]) }}" class="hover:underline">Back</a>
                    <x-fe-button>Save</x-fe-button>
                </div>
            </form>
        </div>
        <form method="POST" action="{{ route('map_layers.destroy', ['map_layer' => $map_layer->id]) }}" onsubmit="return confirm('Do you really want to delete this layer and all its entries?');">
            @csrf
            @method('delete')
            <input type="hidden" name="map_id" value="{{ $map_layer->map->id }}">
            <button class="absolute bottom-4 border border-red-500 bg-red-500 text-white hover:bg-white hover:text-red-500 p-1 px-6 transition uppercase text-xs ml-4" type="submit">Delete Layer</button>
        </form>
    </aside>

    <div class="w-2/3 h-screen bg-gray-200"></div>
</div>
@endsection